openapi: 3.1.0
info:
  contact:
    email: hello@opal.dev
    name: Opal Team
    url: https://www.opal.dev/
  description: The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.
  title: Opal access-rules configuration-templates API
  version: '1.0'
servers:
- description: Production
  url: https://api.opal.dev/v1
tags:
- name: configuration-templates
  description: Operations related to configuration templates
paths:
  /configuration-templates:
    get:
      description: Returns a list of `ConfigurationTemplate` objects.
      operationId: getConfigurationTemplates
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedConfigurationTemplateList'
          description: One page worth of configuration templates for your organization.
      security:
      - BearerAuth: []
      tags:
      - configuration-templates
    post:
      description: Creates a configuration template.
      operationId: createConfigurationTemplate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConfigurationTemplateInfo'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigurationTemplate'
          description: The configuration template just created.
      security:
      - BearerAuth: []
      tags:
      - configuration-templates
    put:
      description: Update a configuration template.
      operationId: updateConfigurationTemplate
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigurationTemplate'
          description: The configuration template just updated.
      requestBody:
        description: Configuration template to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateConfigurationTemplateInfo'
      security:
      - BearerAuth: []
      tags:
      - configuration-templates
  /configuration-templates/{configuration_template_id}:
    delete:
      description: Deletes a configuration template.
      operationId: deleteConfigurationTemplate
      parameters:
      - description: The ID of the configuration template.
        example: 4baf8423-db0a-4037-a4cf-f79c60cb67a5
        explode: false
        in: path
        name: configuration_template_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        '200':
          description: The configuration template was successfully deleted.
      security:
      - BearerAuth: []
      tags:
      - configuration-templates
components:
  schemas:
    ConfigurationTemplate:
      description: '# Configuration Template Object

        ### Description

        The `ConfigurationTemplate` object is used to represent a configuration template.


        ### Usage Example

        Returned from the `GET Configuration Templates` endpoint.'
      example:
        configuration_template_id: 7c86c85d-0651-43e2-a748-d69d658418e8
        admin_owner_id: 7c86c85d-0651-43e2-a748-d69d658418e8
        visibility: private
        linked_audit_message_channel_ids:
        - 37cb7e41-12ba-46da-92ff-030abe0450b1
        - 37cb7e41-12ba-46da-92ff-030abe0450b2
        request_configuration_id: 7c86c85d-0651-43e2-a748-d69d658418e8
        member_oncall_schedule_ids:
        - 37cb7e41-12ba-46da-92ff-030abe0450b1
        - 37cb7e41-12ba-46da-92ff-030abe0450b2
        break_glass_user_ids:
        - 37cb7e41-12ba-46da-92ff-030abe0450b1
        - 37cb7e41-12ba-46da-92ff-030abe0450b2
        require_mfa_to_approve: false
        require_mfa_to_connect: false
        name: Prod AWS Template
      properties:
        configuration_template_id:
          description: The ID of the configuration template.
          example: 7c86c85d-0651-43e2-a748-d69d658418e8
          format: uuid
          type: string
        name:
          description: The name of the configuration template.
          example: Prod AWS Template
          type: string
        admin_owner_id:
          description: The ID of the owner of the configuration template.
          example: 7c86c85d-0651-43e2-a748-d69d658418e8
          format: uuid
          type: string
        visibility:
          description: The visibility info of the configuration template.
          example: private
          $ref: '#/components/schemas/VisibilityInfo'
        linked_audit_message_channel_ids:
          description: The IDs of the audit message channels linked to the configuration template.
          example:
          - 37cb7e41-12ba-46da-92ff-030abe0450b1
          - 37cb7e41-12ba-46da-92ff-030abe0450b2
          items:
            type: string
            format: uuid
          type: array
        request_configuration_id:
          description: The ID of the request configuration linked to the configuration template.
          example: 7c86c85d-0651-43e2-a748-d69d658418e8
          format: uuid
          type: string
        member_oncall_schedule_ids:
          description: The IDs of the on-call schedules linked to the configuration template.
          example:
          - 37cb7e41-12ba-46da-92ff-030abe0450b1
          - 7c86c85d-0651-43e2-a748-d69d658418e8
          items:
            type: string
            format: uuid
          type: array
        break_glass_user_ids:
          description: The IDs of the break glass users linked to the configuration template.
          example:
          - 37cb7e41-12ba-46da-92ff-030abe0450b1
          - 37cb7e41-12ba-46da-92ff-030abe0450b2
          items:
            type: string
            format: uuid
          type: array
        require_mfa_to_approve:
          description: A bool representing whether or not to require MFA for reviewers to approve requests for this configuration template.
          example: false
          type: boolean
        require_mfa_to_connect:
          description: A bool representing whether or not to require MFA to connect to resources associated with this configuration template.
          example: false
          type: boolean
        ticket_propagation:
          $ref: '#/components/schemas/TicketPropagationConfiguration'
        custom_request_notification:
          description: Custom request notification sent upon request approval for this configuration template.
          type: string
          maxLength: 800
          nullable: true
          example: Check your email to register your account.
    CreateRequestConfigurationInfoList:
      description: '# CreateRequestConfigurationInfoList Object

        ### Description

        The `CreateRequestConfigurationInfoList` object is used as an input to the CreateRequestConfigurations API.


        ### Formatting Requirements

        The `CreateRequestConfigurationInfoList` object must contain a list of `RequestConfiguration` objects.

        Exactly one default `RequestConfiguration` must be provided.  A default `RequestConfiguration` is one with a `condition` of `null`

        and a `priority` of `0`.  The default `RequestConfiguration` will be used when no other `RequestConfiguration` matches the request.


        Only one `RequestConfiguration` may be provided for each priority, and the priorities must be contiguous.  For example, if there are

        two `RequestConfigurations` with priorities 0 and 2, there must be a `RequestConfiguration` with priority 1.


        To use the `condition` field, the `condition` must be a valid JSON object.


        The `condition` must be a JSON object with the key `group_ids` (more options may be added in the future), whose value is a list of

        group IDs.

        The `condition` will match if the user requesting access is a member of any of the groups in the list. Currently, we only support

        using a single group as a condition.'
      example:
        request_configurations:
        - request_configuration_id: 7c86c85d-0651-43e2-a748-d69d658418e8
          organization_id: w86c85d-0651-43e2-a748-d69d658418e8
          condition: null
          allow_requests: true
          auto_approval: false
          require_mfa_to_request: false
          max_duration_minutes: 120
          recommended_duration_minutes: 120
          require_support_ticket: false
          reviewer_stages:
          - reviewer_stage_id: 7c86c85d-0651-43e2-a748-d69d658418e8
            owner_ids:
            - 37cb7e41-12ba-46da-92ff-030abe0450b1
            - 37cb7e41-12ba-46da-92ff-030abe0450b2
            stage: 1
          priority: 0
        - request_configuration_id: 7c86c85d-0651-43e2-a748-d69d658418e9
          organization_id: w86c85d-0651-43e2-a748-d69d658418e8
          condition:
            group_id: 1b978423-db0a-4037-a4cf-f79c60cb67b4
          allow_requests: true
          auto_approval: false
          require_mfa_to_request: false
          max_duration_minutes: 120
          recommended_duration_minutes: 120
          require_support_ticket: false
          reviewer_stages:
          - reviewer_stage_id: 7c86c85d-0651-43e2-a748-d69d658418e8
            owner_ids:
            - 37cb7e41-12ba-46da-92ff-030abe0450b1
            - 37cb7e41-12ba-46da-92ff-030abe0450b2
            stage: 1
          priority: 1
      properties:
        request_configurations:
          description: A list of request configurations to create.
          items:
            $ref: '#/components/schemas/RequestConfiguration'
          type: array
      type: object
      required:
      - request_configurations
    VisibilityInfo:
      description: Visibility infomation of an entity.
      example:
        visibility: LIMITED
        visibility_group_ids:
        - 7870617d-e72a-47f5-a84c-693817ab4567
        - 1520617d-e72a-47f5-a84c-693817ab48ad2
      properties:
        visibility:
          $ref: '#/components/schemas/VisibilityTypeEnum'
        visibility_group_ids:
          items:
            type: string
            format: uuid
          type: array
      type: object
      required:
      - visibility
    PaginatedConfigurationTemplateList:
      description: '# PaginatedConfigurationTemplateList Object

        ### Description

        The `PaginatedConfigurationTemplateList` object is used to store a list of configuration templates.


        ### Usage Example

        Returned from the `GET Configuration Templates` endpoint.'
      example:
        results:
        - configuration_template_id: 7c86c85d-0651-43e2-a748-d69d658418e8
          admin_owner_id: a4d7d928-783e-4599-8ec6-088d635af4ac
          visibility: private
          linked_audit_message_channel_ids:
          - l3cb7e41-12ba-46da-92ff-030abe0450b1
          - f3cb7e41-12ba-46da-92ff-030abe0450b2
          request_configuration_id: r3cb7e41-12ba-46da-92ff-030abe0450b1
          member_oncall_schedule_ids:
          - 23cb7e41-12ba-46da-92ff-030abe0450b1
          - m3cb7e41-12ba-46da-92ff-030abe0450b2
          break_glass_user_ids:
          - 63cb7e41-12ba-46da-92ff-030abe0450b1
          - b3cb7e41-12ba-46da-92ff-030abe0450b2
          require_mfa_to_approve: false
          require_mfa_to_connect: false
      properties:
        results:
          items:
            $ref: '#/components/schemas/ConfigurationTemplate'
          type: array
    RequestConfiguration:
      description: '# Request Configuration Object

        ### Description

        The `RequestConfiguration` object is used to represent a request configuration.


        ### Usage Example

        Returned from the `GET Request Configurations` endpoint.'
      example:
        request_configuration_id: 7c86c85d-0651-43e2-a748-d69d658418e8
        organization_id: w86c85d-0651-43e2-a748-d69d658418e8
        created_at: 2021-01-06 20:00:00+00:00
        updated_at: 2021-01-06 20:00:00+00:00
        condition:
          group_id: 1b978423-db0a-4037-a4cf-f79c60cb67b3
        allow_requests: true
        auto_approval: false
        require_mfa_to_request: false
        max_duration_minutes: 120
        recommended_duration_minutes: 120
        require_support_ticket: false
        reviewer_stages:
        - reviewer_stage_id: 7c86c85d-0651-43e2-a748-d69d658418e8
          owner_ids:
          - 37cb7e41-12ba-46da-92ff-030abe0450b1
          - 37cb7e41-12ba-46da-92ff-030abe0450b2
          stage: 1
        priority: 1
      type: object
      properties:
        condition:
          description: The condition for the request configuration.
          $ref: '#/components/schemas/Condition'
        allow_requests:
          description: A bool representing whether or not to allow requests for this resource.
          example: true
          type: boolean
        auto_approval:
          description: A bool representing whether or not to automatically approve requests for this resource.
          example: false
          type: boolean
        require_mfa_to_request:
          description: A bool representing whether or not to require MFA for requesting access to this resource.
          example: false
          type: boolean
        max_duration_minutes:
          description: The maximum duration for which the resource can be requested (in minutes).
          type: integer
          example: 120
        recommended_duration_minutes:
          description: The recommended duration for which the resource should be requested (in minutes). -1 represents an indefinite duration.
          type: integer
          example: 120
        require_support_ticket:
          description: A bool representing whether or not access requests to the resource require an access ticket.
          example: false
          type: boolean
        extensions_duration_in_minutes:
          description: The duration for which access can be extended (in minutes). Set to 0 to disable extensions. When > 0, extensions are enabled for the specified duration.
          type: integer
          example: 120
        request_template_id:
          description: The ID of the associated request template.
          example: 06851574-e50d-40ca-8c78-f72ae6ab4304
          format: uuid
          type: string
        reviewer_stages:
          description: The list of reviewer stages for the request configuration.
          items:
            $ref: '#/components/schemas/ReviewerStage'
          type: array
        priority:
          description: The priority of the request configuration.
          example: 1
          type: integer
      required:
      - organization_id
      - allow_requests
      - auto_approval
      - require_mfa_to_request
      - require_support_ticket
      - priority
    UpdateConfigurationTemplateInfo:
      description: '# UpdateConfigurationTemplateInfo Object

        ### Description

        The `ConfigurationTemplate` object is used to represent an update to a configuration template.


        ### Usage Example

        Use in the `PUT Configuration Templates` endpoint.'
      example:
        configuration_template_id: 7c86c85d-0651-43e2-a748-d69d658418e8
        admin_owner_id: 7c86c85d-0651-43e2-a748-d69d658418e8
        visibility: private
        linked_audit_message_channel_ids:
        - 37cb7e41-12ba-46da-92ff-030abe0450b1
        - 37cb7e41-12ba-46da-92ff-030abe0450b2
        request_configuration_id: 7c86c85d-0651-43e2-a748-d69d658418e8
        member_oncall_schedule_ids:
        - 37cb7e41-12ba-46da-92ff-030abe0450b1
        - 37cb7e41-12ba-46da-92ff-030abe0450b2
        break_glass_user_ids:
        - 37cb7e41-12ba-46da-92ff-030abe0450b1
        - 37cb7e41-12ba-46da-92ff-030abe0450b2
        require_mfa_to_approve: false
        require_mfa_to_connect: false
        name: Prod AWS Template
      required:
      - configuration_template_id
      properties:
        configuration_template_id:
          description: The ID of the configuration template.
          example: 7c86c85d-0651-43e2-a748-d69d658418e8
          format: uuid
          type: string
        name:
          description: The name of the configuration template.
          example: Prod AWS Template
          type: string
        admin_owner_id:
          description: The ID of the owner of the configuration template.
          example: 7c86c85d-0651-43e2-a748-d69d658418e8
          format: uuid
          type: string
        visibility:
          description: The visibility info of the configuration template.
          example: private
          $ref: '#/components/schemas/VisibilityInfo'
        linked_audit_message_channel_ids:
          description: The IDs of the audit message channels linked to the configuration template.
          example:
          - 37cb7e41-12ba-46da-92ff-030abe0450b1
          - 37cb7e41-12ba-46da-92ff-030abe0450b2
          items:
            type: string
            format: uuid
          type: array
        request_configurations:
          type: array
          items:
            $ref: '#/components/schemas/RequestConfiguration'
          description: The request configuration list linked to the configuration template.
        request_configuration_list:
          description: The request configuration list linked to the configuration template. Deprecated in favor of `request_configurations`.
          $ref: '#/components/schemas/CreateRequestConfigurationInfoList'
          deprecated: true
          example:
            request_configurations:
            - request_configuration_id: 7c86c85d-0651-43e2-a748-d69d658418e8
              organization_id: w86c85d-0651-43e2-a748-d69d658418e8
              condition: null
              allow_requests: true
              auto_approval: false
              require_mfa_to_request: false
              max_duration_minutes: 120
              recommended_duration_minutes: 120
              require_support_ticket: false
              reviewer_stages:
              - reviewer_stage_id: 7c86c85d-0651-43e2-a748-d69d658418e8
                owner_ids:
                - 37cb7e41-12ba-46da-92ff-030abe0450b1
                - 37cb7e41-12ba-46da-92ff-030abe0450b2
                stage: 1
              priority: 0
            - request_configuration_id: 7c86c85d-0651-43e2-a748-d69d658418e9
              organization_id: w86c85d-0651-43e2-a748-d69d658418e8
              condition:
                group_id: 1b978423-db0a-4037-a4cf-f79c60cb67b4
              allow_requests: true
              auto_approval: false
              require_mfa_to_request: false
              max_duration_minutes: 120
              recommended_duration_minutes: 120
              require_support_ticket: false
              reviewer_stages:
              - reviewer_stage_id: 7c86c85d-0651-43e2-a748-d69d658418e8
                owner_ids:
                - 37cb7e41-12ba-46da-92ff-030abe0450b1
                - 37cb7e41-12ba-46da-92ff-030abe0450b2
                stage: 1
              priority: 1
        member_oncall_schedule_ids:
          description: The IDs of the on-call schedules linked to the configuration template.
          example:
          - 37cb7e41-12ba-46da-92ff-030abe0450b1
          - 7c86c85d-0651-43e2-a748-d69d658418e8
          items:
            type: string
            format: uuid
          type: array
        break_glass_user_ids:
          description: The IDs of the break glass users linked to the configuration template.
          example:
          - 37cb7e41-12ba-46da-92ff-030abe0450b1
          - 37cb7e41-12ba-46da-92ff-030abe0450b2
          items:
            type: string
            format: uuid
          type: array
        require_mfa_to_approve:
          description: A bool representing whether or not to require MFA for reviewers to approve requests for this configuration template.
          example: false
          type: boolean
        require_mfa_to_connect:
          description: A bool representing whether or not to require MFA to connect to resources associated with this configuration template.
          example: false
          type: boolean
        ticket_propagation:
          $ref: '#/components/schemas/TicketPropagationConfiguration'
        custom_request_notification:
          description: Custom request notification sent upon request approval for this configuration template.
          type: string
          maxLength: 800
          nullable: true
          example: Check your email to register your account.
    Condition:
      description: '# Condition Object

        ### Description

        The `Condition` object is used to represent a condition.


        ### Usage Example

        Used to match request configurations to users in `RequestConfiguration`'
      example:
        group_ids:
        - 1b978423-db0a-4037-a4cf-f79c60cb67b3
      type: object
      properties:
        group_ids:
          description: The list of group IDs to match.
          example:
          - 1b978423-db0a-4037-a4cf-f79c60cb67b3
          items:
            type: string
            format: uuid
          type: array
        role_remote_ids:
          description: The list of role remote IDs to match.
          example:
          - arn:aws:iam::590304332660:role/AdministratorAccess
          type: array
          items:
            type: string
    VisibilityTypeEnum:
      description: The visibility level of the entity.
      enum:
      - GLOBAL
      - LIMITED
      example: GLOBAL
      type: string
    TicketPropagationConfiguration:
      description: Configuration for ticket propagation, when enabled, a ticket will be created for access changes related to the users in this resource.
      type: object
      properties:
        enabled_on_grant:
          type: boolean
        enabled_on_revocation:
          type: boolean
        ticket_provider:
          $ref: '#/components/schemas/TicketingProviderEnum'
        ticket_project_id:
          type: string
      required:
      - enabled_on_grant
      - enabled_on_revocation
    CreateConfigurationTemplateInfo:
      description: '# CreateConfigurationTemplateInfo Object

        ### Description

        The `CreateConfigurationTemplateInfo` object is used to store creation info for a configuration template.


        ### Usage Example

        Use in the `POST Configuration Templates` endpoint.'
      example:
        admin_owner_id: 7c86c85d-0651-43e2-a748-d69d658418e8
        visibility: private
        linked_audit_message_channel_ids:
        - 37cb7e41-12ba-46da-92ff-030abe0450b1
        - 37cb7e41-12ba-46da-92ff-030abe0450b2
        request_configuration_id: 7c86c85d-0651-43e2-a748-d69d658418e8
        member_oncall_schedule_ids:
        - 37cb7e41-12ba-46da-92ff-030abe0450b1
        - 37cb7e41-12ba-46da-92ff-030abe0450b2
        break_glass_user_ids:
        - 37cb7e41-12ba-46da-92ff-030abe0450b1
        - 37cb7e41-12ba-46da-92ff-030abe0450b2
        require_mfa_to_approve: false
        require_mfa_to_connect: false
        name: Prod AWS Template
      required:
      - admin_owner_id
      - visibility
      - name
      - require_mfa_to_approve
      - require_mfa_to_connect
      properties:
        admin_owner_id:
          description: The ID of the owner of the configuration template.
          example: 7c86c85d-0651-43e2-a748-d69d658418e8
          format: uuid
          type: string
        visibility:
          description: The visibility info of the configuration template.
          example: private
          $ref: '#/components/schemas/VisibilityInfo'
        linked_audit_message_channel_ids:
          description: The IDs of the audit message channels linked to the configuration template.
          example:
          - 37cb7e41-12ba-46da-92ff-030abe0450b1
          - 37cb7e41-12ba-46da-92ff-030abe0450b2
          items:
            type: string
            format: uuid
          type: array
        member_oncall_schedule_ids:
          description: The IDs of the on-call schedules linked to the configuration template.
          example:
          - 37cb7e41-12ba-46da-92ff-030abe0450b1
          - 37cb7e41-12ba-46da-92ff-030abe0450b2
          items:
            type: string
            format: uuid
          type: array
        break_glass_user_ids:
          description: The IDs of the break glass users linked to the configuration template.
          example:
          - 37cb7e41-12ba-46da-92ff-030abe0450b1
          - 37cb7e41-12ba-46da-92ff-030abe0450b2
          items:
            type: string
            format: uuid
          type: array
        require_mfa_to_approve:
          description: A bool representing whether or not to require MFA for reviewers to approve requests for this configuration template.
          example: false
          type: boolean
        require_mfa_to_connect:
          description: A bool representing whether or not to require MFA to connect to resources associated with this configuration template.
          example: false
          type: boolean
        name:
          description: The name of the configuration template.
          example: Prod AWS Template
          type: string
        request_configurations:
          type: array
          items:
            $ref: '#/components/schemas/RequestConfiguration'
          description: The request configuration list of the configuration template. If not provided, the default request configuration will be used.
        request_configuration_list:
          description: The request configuration list of the configuration template. If not provided, the default request configuration will be used. Deprecated in favor of `request_configurations`.
          $ref: '#/components/schemas/CreateRequestConfigurationInfoList'
          deprecated: true
          example:
            request_configurations:
            - request_configuration_id: 7c86c85d-0651-43e2-a748-d69d658418e8
              organization_id: w86c85d-0651-43e2-a748-d69d658418e8
              condition: null
              allow_requests: true
              auto_approval: false
              require_mfa_to_request: false
              max_duration_minutes: 120
              recommended_duration_minutes: 120
              require_support_ticket: false
              reviewer_stages:
              - reviewer_stage_id: 7c86c85d-0651-43e2-a748-d69d658418e8
                owner_ids:
                - 37cb7e41-12ba-46da-92ff-030abe0450b1
                - 37cb7e41-12ba-46da-92ff-030abe0450b2
                stage: 1
              priority: 0
            - request_configuration_id: 7c86c85d-0651-43e2-a748-d69d658418e9
              organization_id: w86c85d-0651-43e2-a748-d69d658418e8
              condition:
                group_id: 1b978423-db0a-4037-a4cf-f79c60cb67b4
              allow_requests: true
              auto_approval: false
              require_mfa_to_request: false
              max_duration_minutes: 120
              recommended_duration_minutes: 120
              require_support_ticket: false
              reviewer_stages:
              - reviewer_stage_id: 7c86c85d-0651-43e2-a748-d69d658418e8
                owner_ids:
                - 37cb7e41-12ba-46da-92ff-030abe0450b1
                - 37cb7e41-12ba-46da-92ff-030abe0450b2
                stage: 1
              priority: 1
        ticket_propagation:
          $ref: '#/components/schemas/TicketPropagationConfiguration'
        custom_request_notification:
          description: Custom request notification sent upon request approval for this configuration template.
          type: string
          maxLength: 800
          nullable: true
          example: Check your email to register your account.
    TicketingProviderEnum:
      description: The third party ticketing platform provider.
      enum:
      - JIRA
      - LINEAR
      - SERVICE_NOW
      example: LINEAR
      type: string
    ReviewerStage:
      description: A reviewer stage.
      example:
        owner_ids:
        - 7870617d-e72a-47f5-a84c-693817ab4567
        - 1520617d-e72a-47f5-a84c-693817ab48ad2
        service_user_ids:
        - 7870617d-e72a-47f5-a84c-693817ab4568
      properties:
        require_manager_approval:
          description: Whether this reviewer stage should require manager approval.
          example: false
          type: boolean
        require_admin_approval:
          description: Whether this reviewer stage should require admin approval.
          example: false
          type: boolean
        operator:
          description: The operator of the reviewer stage. Admin and manager approval are also treated as reviewers.
          enum:
          - AND
          - OR
          example: AND
          type: string
        owner_ids:
          description: The IDs of owners assigned as reviewers for this stage.
          items:
            type: string
            format: uuid
          type: array
        service_user_ids:
          description: The IDs of service users assigned as reviewers for this stage.
          items:
            type: string
            format: uuid
          type: array
      type: object
      required:
      - operator
      - require_manager_approval
      - owner_ids
      - stage
  securitySchemes:
    BearerAuth:
      scheme: bearer
      type: http
